services:
  core:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-files: "3"
    env_file:
      - /etc/langops-api/secrets.env
    restart: unless-stopped
